# Generated by Django 4.2.10 on 2024-02-20 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('station_id', models.AutoField(primary_key=True, serialize=False)),
                ('station_name', models.CharField(max_length=100)),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField()),
                ('service_start', models.CharField(max_length=100)),
                ('service_ends', models.CharField(max_length=100)),
                ('num_stations', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TrainStop',
            fields=[
                ('train_stop_id', models.AutoField(primary_key=True, serialize=False)),
                ('arrival_time', models.CharField(max_length=100)),
                ('departure_time', models.CharField(max_length=100)),
                ('fare', models.IntegerField()),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.station')),
                ('train', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.train')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBooked',
            fields=[
                ('ticket_id', models.AutoField(primary_key=True, serialize=False)),
                ('timestamp', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user')),
            ],
        ),
    ]
