# Generated by Django 5.0.2 on 2024-02-23 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_user_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
