# Generated by Django 5.0.2 on 2024-02-23 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_station_station_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='service_ends',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='train',
            name='service_start',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
