# Generated by Django 5.0.2 on 2024-02-23 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_alter_train_service_ends_alter_train_service_start'),
    ]

    operations = [
        migrations.AlterField(
            model_name='train',
            name='num_stations',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
