# Generated by Django 5.0.2 on 2024-02-23 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_train_num_stations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketbooked',
            name='ticket_id',
            field=models.IntegerField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='trainstop',
            name='train_stop_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(),
        ),
    ]
