# Generated by Django 5.0.2 on 2024-02-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_ticketbooked_ticket_id_alter_train_train_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='station',
            name='station_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ticketbooked',
            name='ticket_id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='train',
            name='num_stations',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='train',
            name='service_ends',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='service_start',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AlterField(
            model_name='train',
            name='train_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='trainstop',
            name='train_stop_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.IntegerField(verbose_name=''),
        ),
    ]
