# Generated by Django 5.0.2 on 2024-02-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_alter_station_station_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainstop',
            name='arrival_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainstop',
            name='departure_time',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='trainstop',
            name='fare',
            field=models.IntegerField(null=True),
        ),
    ]
